#include "../../includes/Command.hpp"

void Command::ACCEPT(std::string buffer){(void)buffer; return;};
void Command::ACTION(std::string buffer){(void)buffer; return;};
void Command::ADMIN(std::string buffer){(void)buffer; return;};
void Command::ALIAS(std::string buffer){(void)buffer; return;};
void Command::AWAY(std::string buffer){(void)buffer; return;};
void Command::BAN(std::string buffer){(void)buffer; return;};
void Command::BEEP(std::string buffer){(void)buffer; return;};
void Command::BIND(std::string buffer){(void)buffer; return;};
void Command::CAT(std::string buffer){(void)buffer; return;};
void Command::CD(std::string buffer){(void)buffer; return;};
void Command::CHANNEL(std::string buffer){(void)buffer; return;};
void Command::CLEAR(std::string buffer){(void)buffer; return;};
void Command::COMPLETION(std::string buffer){(void)buffer; return;};
void Command::CONNECT(std::string buffer){(void)buffer; return;};
void Command::CTCP(std::string buffer){(void)buffer; return;};
void Command::CYCLE(std::string buffer){(void)buffer; return;};
void Command::DCC(std::string buffer){(void)buffer; return;};
void Command::DEOP(std::string buffer){(void)buffer; return;};
void Command::DEVOICE(std::string buffer){(void)buffer; return;};
void Command::DEHILIGHT(std::string buffer){(void)buffer; return;};
void Command::DISCONNECT(std::string buffer){(void)buffer; return;};
void Command::ECHO(std::string buffer){(void)buffer; return;};
void Command::EVAL(std::string buffer){(void)buffer; return;};
void Command::EXEC(std::string buffer){(void)buffer; return;};
void Command::FLUSHBUFFER(std::string buffer){(void)buffer; return;};
void Command::FOREACH(std::string buffer){(void)buffer; return;};
void Command::FORMAT(std::string buffer){(void)buffer; return;};
void Command::HASH(std::string buffer){(void)buffer; return;};
void Command::HELP(std::string buffer){(void)buffer; return;};
void Command::HILIGHT(std::string buffer){(void)buffer; return;};
void Command::IGNORE(std::string buffer){(void)buffer; return;};
void Command::INFO(std::string buffer){(void)buffer; return;};
void Command::INVITE(std::string buffer){(void)buffer; return;};
void Command::IRCNET(std::string buffer){(void)buffer; return;};
void Command::ISO(std::string buffer){(void)buffer; return;};
void Command::NJOIN(std::string buffer){(void)buffer; return;};
void Command::KICK(std::string buffer){(void)buffer; return;};
void Command::KICKBAN(std::string buffer){(void)buffer; return;};
void Command::KILL(std::string buffer){(void)buffer; return;};
void Command::KNOCK(std::string buffer){(void)buffer; return;};
void Command::KNOCKOUT(std::string buffer){(void)buffer; return;};
void Command::LASTLOG(std::string buffer){(void)buffer; return;};
void Command::LAYOUT(std::string buffer){(void)buffer; return;};
void Command::LINKS(std::string buffer){(void)buffer; return;};
void Command::LIST(std::string buffer){(void)buffer; return;};
void Command::LOAD(std::string buffer){(void)buffer; return;};
void Command::LASTLOGLUSERS(std::string buffer){(void)buffer; return;};
void Command::MAP(std::string buffer){(void)buffer; return;};
void Command::ME(std::string buffer){(void)buffer; return;};
void Command::MIRCDCC(std::string buffer){(void)buffer; return;};
void Command::Command::MODE(std::string buffer){(void)buffer; std::cout << "WWWWWWWWWWWWWWWWWWWWWWWW" << std::endl;return ;};
void Command::MOTD(std::string buffer){(void)buffer; return;};
void Command::MSG(std::string buffer){(void)buffer; return;};
void Command::NAMES(std::string buffer){(void)buffer; return;};
void Command::NCTCP(std::string buffer){(void)buffer; return;};
void Command::NETSPLIT(std::string buffer){(void)buffer; return;};
void Command::NETWORK(std::string buffer){(void)buffer; return;};
void Command::NICK(std::string buffer){(void)buffer; return;};
void Command::NOTICE(std::string buffer){(void)buffer; return;};
void Command::NOTIFY(std::string buffer){(void)buffer; return;};
void Command::OP(std::string buffer){(void)buffer; return;};
void Command::OPER(std::string buffer){(void)buffer; return;};
void Command::PART(std::string buffer){(void)buffer; return;};
void Command::Command::PING(std::string buffer){(void)buffer; std::cout << "EEEEEEEEEEEEEEE" << std::endl;return ;};
void Command::QUERY(std::string buffer){(void)buffer; return;};
void Command::QUIT(std::string buffer){(void)buffer; return;};
void Command::QUOTE(std::string buffer){(void)buffer; return;};
void Command::RAWLOG(std::string buffer){(void)buffer; return;};
void Command::RECODE(std::string buffer){(void)buffer; return;};
void Command::RECONNECT(std::string buffer){(void)buffer; return;};
void Command::REDRAW(std::string buffer){(void)buffer; return;};
void Command::REHASH(std::string buffer){(void)buffer; return;};
void Command::RELOAD(std::string buffer){(void)buffer; return;};
void Command::RESIZE(std::string buffer){(void)buffer; return;};
void Command::RESTART(std::string buffer){(void)buffer; return;};
void Command::RMRECONNS(std::string buffer){(void)buffer; return;};
void Command::RMREJOINS(std::string buffer){(void)buffer; return;};
void Command::SAVE(std::string buffer){(void)buffer; return;};
void Command::SCONNECT(std::string buffer){(void)buffer; return;};
void Command::SCRIPT(std::string buffer){(void)buffer; return;};
void Command::SCROLLBACK(std::string buffer){(void)buffer; return;};
void Command::SERVER(std::string buffer){(void)buffer; return;};
void Command::SERVLIST(std::string buffer){(void)buffer; return;};
void Command::SET(std::string buffer){(void)buffer; return;};
void Command::SETHOST(std::string buffer){(void)buffer; return;};
void Command::SILENCE(std::string buffer){(void)buffer; return;};
void Command::SQUERY(std::string buffer){(void)buffer; return;};
void Command::SQUIT(std::string buffer){(void)buffer; return;};
void Command::STATS(std::string buffer){(void)buffer; return;};
void Command::STATUSBAR(std::string buffer){(void)buffer; return;};
void Command::TIME(std::string buffer){(void)buffer; return;};
void Command::TOGGLE(std::string buffer){(void)buffer; return;};
void Command::TOPIC(std::string buffer){(void)buffer; return;};
void Command::TRACE(std::string buffer){(void)buffer; return;};
void Command::TS(std::string buffer){(void)buffer; return;};
void Command::UNALIAS(std::string buffer){(void)buffer; return;};
void Command::UNBAN(std::string buffer){(void)buffer; return;};
void Command::UNIGNORE(std::string buffer){(void)buffer; return;};
void Command::UNLOAD(std::string buffer){(void)buffer; return;};
void Command::UNNOTIFY(std::string buffer){(void)buffer; return;};
void Command::UNQUERY(std::string buffer){(void)buffer; return;};
void Command::UNSILENCE(std::string buffer){(void)buffer; return;};
void Command::UPGRADE(std::string buffer){(void)buffer; return;};
void Command::UPTIME(std::string buffer){(void)buffer; return;};
void Command::USERHOST(std::string buffer){(void)buffer; return;};
void Command::VER(std::string buffer){(void)buffer; return;};
void Command::VERSION(std::string buffer){(void)buffer; return;};
void Command::VOICE(std::string buffer){(void)buffer; return;};
void Command::WAIT(std::string buffer){(void)buffer; return;};
void Command::WALL(std::string buffer){(void)buffer; return;};
void Command::WALLOPS(std::string buffer){(void)buffer; return;};
void Command::WHO(std::string buffer){(void)buffer; return;};
void Command::WHOIS(std::string buffer){(void)buffer; return;};
void Command::WHOWAS(std::string buffer){(void)buffer; return;};
void Command::WINDOW(std::string buffer){(void)buffer; return;};

Command::Command(void){
    this->_commandsFilled["PING"] = PING;
    this->_commandsFilled["MODE"] = MODE;
};

Command::~Command(void){

};